### ISSUE TITLE
(SURE-5510) Unable to upgrade an imported AKS cluster from Rancher GUI

### ISSUE THREAD

**Issue by kkaempf** [rancher/aks-operator#166]
#### Issue description:

We are trying to upgrade from Rancher GUI an imported AKS cluster (1.22.15 to 1.23.8) but unfortunately, nothing happens and the aks-config-operator is crashing in "CrashLoopBackOff" state.

#### Repro steps:

create AKS cluster (1.22.11) via terraform or azure portal
rancher 2.6.8 > import existing cluster > upgrade imported cluster from 1.22.11 to 1.22.15 

Workaround:
Is workararound available and implemented? yes
What is the workaround:

steps :

1. upgrade control planes from Azure GUI and

2. upgrade workers from Rancher GUI.

#### Actual behavior:
The upgrade is not happening and the  aks-config-operator is crashing

#### Expected behavior:
The upgrade should happen without any issues.

#### Files, logs, traces:

```
[aks-config-operator-7dc976c58c-n8cvx] time="2022-11-02T15:25:45Z" level=info msg="Checking configuration for cluster [azuk8s-devops-aks-dev]" [aks-config-operator-7dc976c58c-n8cvx] time="2022-11-02T15:25:46Z" level=info msg="Updating kubernetes version for cluster [azuk8s-devops-aks-dev]" [aks-config-operator-7dc976c58c-n8cvx] E1102 15:25:47.010451 8 runtime.go:79] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map) [aks-config-operator-7dc976c58c-n8cvx] goroutine 31 [running]: [aks-config-operator-7dc976c58c-n8cvx]

[k8s.io/apimachinery/pkg/util/runtime.logPanic](https://k8s.io/apimachinery/pkg/util/runtime.logPanic)

({0x13bd1a0, 0x170e640}) [aks-config-operator-7dc976c58c-n8cvx] /go/pkg/mod/

[k8s.io/apimachinery@v0.24.1/pkg/util/runtime/runtime.go:75](https://k8s.io/apimachinery@v0.24.1/pkg/util/runtime/runtime.go:75)

+0x85 [aks-config-operator-7dc976c58c-n8cvx]

[k8s.io/apimachinery/pkg/util/runtime.HandleCrash](https://k8s.io/apimachinery/pkg/util/runtime.HandleCrash)

({0x0, 0x0, 0xc0000b83c0}) [aks-config-operator-7dc976c58c-n8cvx] /go/pkg/mod/

[k8s.io/apimachinery@v0.24.1/pkg/util/runtime/runtime.go:49](https://k8s.io/apimachinery@v0.24.1/pkg/util/runtime/runtime.go:49)

+0x75 [aks-config-operator-7dc976c58c-n8cvx] panic({0x13bd1a0, 0x170e640}
```

#### Additional notes:
Github issue: https://github.com/rancher/rancher/issues/37863

**Comment by kkaempf** [comment]
see #93
